modLoader="javafml" 
loaderVersion="[32,)" 

[[mods]] 

modId="magicmod" 
version="${file.jarVersion}" 
displayName="Magic Mod" 
logoFile="magicmod.png" 
authors="Ian Rehwinkel" 
description='''
A mod that adds magic wands.
'''

[[dependencies.magicmod]] 
    modId="forge" 
    mandatory=true 
    versionRange="[32,)" 
    ordering="NONE"
    side="BOTH"

[[dependencies.magicmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
